# Site settings
# These are used to personalize your new site.
title: Peter Jackson Link, III # your name here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2040)
  <br /><br />
  <a href="https://example.com/resume">View My Resume</a>
  <br /><br />
  <s><a href="#">View My LinkedIn Profile</a></s> I do not use Social Media.
repository: "csci-csu/csci-portfolio"
github_username:  flashcardsmobile-admin # update with your username
google_analytics: UA-000000-0 # I don't believe in harming potential employers by tracking them. This would be equivalent to punching them in the face in the middle of an interview. Completely uncalled for and unprofessional. Whoever put Google Analytics on a Portfolio site template should not be considered an ethical actor.

# Build setting
theme: jekyll-theme-minimal

